backend:
  name: github
  repo: roberlancarvalho/roberlancarvalho.com  # Seu repositório GitHub
  base_url: https://roberlancarvalho.com  # URL base para a autenticação
  auth_endpoint: api/auth  # Endpoint de autenticação correspondente ao Authorization callback URL no GitHub

media_folder: public/assets/img  # Pasta onde os arquivos de mídia serão salvos
public_folder: /assets/img  # Caminho público para acessar os arquivos de mídia

publish_mode: editorial_workflow  # Habilita o modo editorial para rascunhos e revisões

slug:
  encoding: 'ascii'  # Codificação para os slugs
  clean_accents: true  # Remove acentos dos slugs

collections:
  - name: posts  # Nome da coleção, usado nas rotas
    label: Posts  # Rótulo da coleção, usado na interface do usuário
    folder: posts  # Caminho para a pasta onde os documentos são armazenados
    create: true  # Permite aos usuários criar novos documentos nesta coleção
    slug: '{{slug}}'  # Template para o nome do arquivo, baseado no título do documento
    fields:  # Campos para cada documento
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD hh:mm:ss' }
      - { label: 'Post Image', name: 'image', widget: 'image', required: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - label: 'Main Class'
        name: 'main-class'
        widget: 'select'
        options: ['tech', 'leitura', 'js', 'dev', 'code', 'design', 'devops', 'tips', 'ia', 'css', 'dicas', 'ui/ux', 'seg']


      - label: 'Color'
        name: 'color'
        widget: 'select'
        options:
          - { label: 'Dev', value: '#EC407A' }
          - { label: 'Tech', value: '#007BFF' }
          - { label: 'Leitura', value: '#1E88E5' }
          - { label: 'JS', value: '#FFEB3B' }
          - { label: 'Code', value: '#FF9800' }
          - { label: 'Design', value: '#7E57C2' }
          - { label: 'DevOps', value: '#00ACC1' }
          - { label: 'Tips', value: '#8BC34A' }
          - { label: 'IA', value: '#3776AB' }
          - { label: 'CSS', value: '#2196F3' }
          - { label: 'Dicas', value: '#FFC107' }
          - { label: 'UI/UX', value: '#9C27B0' }
          - { label: 'Seg', value: '#F44336' }

      - { label: 'Tags', name: 'tags', widget: 'list', default: [''] }
      - { label: 'Category', name: 'categories', widget: 'list', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
